Add Image media bundle #483
Islandora-CLAW/islandora_image pull request #2
Opened 2017-02-08 22:36 UTC by jyobb

I have added an image media bundle in the config/install directory.

2017-02-09 19:52 UTC, dannylamb commented
This PR looks good @jyobb.  We'll need to add a field to hold the image contents.  Would you like to try and tackle that here?  I can help you out if you'd like.

If not, I'll peel off a separate ticket and we can have it addressed later.

2017-02-09 21:08 UTC, jyobb commented
@dannylamb I would be glad to tackle adding the field to hold contents

2017-02-10 21:21 UTC, whikloj commented
I'd agree that adding the configuration entity and the field definition/storage would be a good thing to add. Otherwise this work is hard to test. 

I mean it installed fine 👍 , just can't use it yet.

@jyobb  you might want to look at [islandora_collection](https://github.com/Islandora-CLAW/islandora_collection/tree/8.x-1.x/config/install) that is an entity with 2 fields defined and you can see the YAML files there.

2017-02-16 19:40 UTC, jyobb commented
@whikloj @dannylamb Should I be able to just copy paste and tweak files from islandora_collection?

2017-02-16 19:51 UTC, whikloj commented
@jyobb you might want to create the field using Drupal's UI and export the configuration instead. 
Only because this is the first field to store an image, those ones in islandora_collection were storing text and entity references.

2017-02-17 16:33 UTC, jyobb commented
@whikloj I have created what I think is an image storage field but would like to run what I have done past you to make sure I'm not totally out to lunch.

2017-02-17 20:58 UTC, jyobb commented
I'm not around Feb.20-24 so if this needs to be done right away someone will need to take it on.

2017-02-21 16:20 UTC, whikloj commented
@jyobb Just throw what you have in here, don't worry about the mess. I have a strict _squash and merge_ policy, so those attempts will fade into the gloriousness of your success.

2017-02-21 16:21 UTC, whikloj commented
@ruebot Can I get access to this repo por favor?

2017-02-22 19:44 UTC, dannylamb commented
@jyobb It's no problem to wait 'til you get back.  Feel free to push up what you have when you can and we'll give it a whirl.

Thx so much for taking this on.  The D8 beast is a big one to wrestle with at first, and I appreciate the effort.

2017-02-28 15:22 UTC, dannylamb commented
@jyobb Antyhing I can do to help you with this?

2017-02-28 16:58 UTC, jyobb commented
I have a fedora Resource Image bundle but cannot see how to add the dependencies. If we could have a quick chat on IRC so I can understand how the yaml file is used that would be very helpful.

2017-02-28 19:16 UTC, dannylamb commented
@jyobb The image and description fields have been made for `fedora_resource` entities.  But for here, all you need is to make the image field for `media` entities.  Specifically the `image` media entity you made with your first commit.  Don't worry about description or making a bundle for `fedora_resource`.

If you visit http://localhost:8000/admin/structure/media/manage/image/fields, you can add the image field there and then export it.  Once its added, you'll also want to configure the `image` bundle to point to it.  You can do so at the 'Type Provider Information' section at: http://localhost:8000/admin/structure/media/manage/image.

2017-02-28 21:07 UTC, jyobb commented
I have removed the Fedora Resource bundle yml files and added Islandora Image media bundle yml files

2017-03-01 17:26 UTC, dannylamb requested changes

2017-03-01 17:26 UTC, dannylamb commented on config/install/field.storage.media.field_image_storage.yml
> +type: file
This needs to be an 'Image' field.  When you go to create the field, it's in the drop-down for field type.  It's pretty much the same as file, except it has some niceties for alt text and displaying the image.

2017-03-01 17:26 UTC, dannylamb commented on config/install/field.field.media.image.field_image_storage.yml
> +  file_extensions: 'png gif jpg jpeg tiff tif jp2'
I did some tests, and for some reason, the field isn't obeying these values.  I don't think it's anything you've done.  It's probably Drupal.  Let's leave the defaults (`png gif jpg jpeg`) until I can take a deeper dive and figure out what's going on.

2017-03-01 17:30 UTC, jyobb commented on config/install/field.storage.media.field_image_storage.yml
> +type: file
Ok. I'll fix it up.

2017-03-01 17:46 UTC, dannylamb commented on config/install/field.field.media.image.field_image_storage.yml
> +dependencies:
Oh, and I forgot.  You need to add a block that looks like this
```
enforced:
  module:
    - islandora_image
```
to the dependencies section of each of your exported yaml files.  This tells drupal to uninstall the config when you uninstall the module.  It makes testing a whole lot easier, too.

Here's an example from the `islandora` repo: https://github.com/Islandora-CLAW/islandora/blob/8.x-1.x/config/install/islandora.fedora_resource_type.rdf_source.yml#L5-L7

2017-03-01 17:55 UTC, jyobb commented on config/install/field.field.media.image.field_image_storage.yml
> +dependencies:
is this done via the web UI? I hunted all over the place for a way to setup the dependencies but could not find anything

2017-03-01 18:47 UTC, dannylamb commented on config/install/field.field.media.image.field_image_storage.yml
> +dependencies:
Sadly, no.  It's a manual process.  I add them in a text editor after exporting them.

2017-03-01 19:52 UTC, dannylamb requested changes

2017-03-01 19:52 UTC, dannylamb commented on config/install/field.field.media.image.field_islandora_image.yml
> +    - islandora_image
this dependency needs to be nested in a enforced block.  the entire chunk should look like this: 
```
dependencies:
  config:
    - field.storage.media.field_islandora_image
    - media_entity.bundle.image
  module:
    - image
  enforced:
    module:
      - islandora_image
```

2017-03-01 19:53 UTC, jyobb commented
@dannylamb I have added the dependency.

2017-03-01 20:18 UTC, jyobb commented
@dannylamb I have corrected the dependency section of the yml files

2017-03-03 15:00 UTC, dannylamb commented
@jyobb pulling these in now to test

2017-03-03 18:20 UTC, dannylamb commented
:+1: Looks good.  Works as expected.

On behalf of CLAW, I'll let Michael Bolton congratulate you on your first contribution!

<image src="https://media.giphy.com/media/l3q2UdX8HREZi35gA/source.gif" width="480" height="270"></image>

2017-03-03 18:20 UTC, merged